
alter session set "_ORACLE_SCRIPT"=true;
 

/*  3, CREAR PERFILES*/

CREATE PROFILE developer LIMIT
		SESSIONS_PER_USER 1
		IDLE_TIME 30
		CONNECT_TIME 60
		FAILED_LOGIN_ATTEMPTS 5
		PASSWORD_LIFE_TIME 90;


CREATE PROFILE web_application LIMIT
		SESSIONS_PER_USER 5
		IDLE_TIME UNLIMITED
		CONNECT_TIME UNLIMITED
		FAILED_LOGIN_ATTEMPTS 2
		PASSWORD_LIFE_TIME 30;



CREATE PROFILE dba_admin LIMIT
		SESSIONS_PER_USER 1
		IDLE_TIME UNLIMITED
		CONNECT_TIME 30
		FAILED_LOGIN_ATTEMPTS 2
		PASSWORD_LIFE_TIME 30;
        


CREATE PROFILE analyst LIMIT
		SESSIONS_PER_USER 1
		IDLE_TIME 5
		CONNECT_TIME 30
		FAILED_LOGIN_ATTEMPTS 3
		PASSWORD_LIFE_TIME 30
        PASSWORD_GRACE_TIME 3;
        
        


CREATE PROFILE support_III LIMIT
		SESSIONS_PER_USER 1
		IDLE_TIME 5
		CONNECT_TIME 240
		FAILED_LOGIN_ATTEMPTS 3
		PASSWORD_LIFE_TIME 20
        PASSWORD_GRACE_TIME 3;
        
        
        

CREATE PROFILE reporter LIMIT
		SESSIONS_PER_USER 1
		IDLE_TIME 15
		CONNECT_TIME 90
		FAILED_LOGIN_ATTEMPTS 4
		PASSWORD_LIFE_TIME UNLIMITED
        PASSWORD_GRACE_TIME 5;
        
        
        
        

CREATE PROFILE auditor LIMIT
		SESSIONS_PER_USER 1
		IDLE_TIME 15
		CONNECT_TIME 90
		FAILED_LOGIN_ATTEMPTS 4
		PASSWORD_LIFE_TIME UNLIMITED
        PASSWORD_GRACE_TIME 5;
        
        
        

