--------------------------------------------------------
-- Archivo creado  - domingo-octubre-20-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APUESTAS
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."APUESTAS" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"FECHA_APUESTA" DATE, 
	"ID_USUARIO" NUMBER(22,0), 
	"TOTAL" NUMBER(22,0), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table AUDITORIA
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."AUDITORIA" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"FECHA_HORA" DATE, 
	"TABLA" VARCHAR2(255 BYTE), 
	"RECORD_ID" NUMBER(22,0), 
	"ACTION" VARCHAR2(255 BYTE), 
	"USUARIO" VARCHAR2(255 BYTE), 
	"IP" VARCHAR2(255 BYTE), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_AUDITING" ;
--------------------------------------------------------
--  DDL for Table BANCOS
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."BANCOS" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table BONOS
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."BONOS" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CODIGO" VARCHAR2(255 BYTE), 
	"VALOR" NUMBER(22,0), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table CIUDADES
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."CIUDADES" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_DEPARTAMENTO" NUMBER(22,0), 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"CODIGO_ZIP" VARCHAR2(255 BYTE), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table COMPROBANTES_DOCUMENTOS
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."COMPROBANTES_DOCUMENTOS" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_USUARIO" NUMBER(22,0), 
	"TIPO" VARCHAR2(255 BYTE), 
	"TAMAÑO" NUMBER(22,2), 
	"EXTENSION" VARCHAR2(255 BYTE), 
	"URL" VARCHAR2(255 BYTE), 
	"ESTADO" VARCHAR2(255 BYTE), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table CRONOGRAMA_PARTIDOS
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."CRONOGRAMA_PARTIDOS" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"FECHA" DATE, 
	"HORA" NUMBER(22,0), 
	"ID_EQUIPO1" NUMBER(22,0), 
	"ID_EQUIPO2" NUMBER(22,0), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table CUENTAS
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."CUENTAS" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_USUARIO" NUMBER(22,0), 
	"SALDO" NUMBER(22,0), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table DEPARTAMENTOS
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."DEPARTAMENTOS" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"ID_PAIS" NUMBER(22,0), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table DEPOSITOS
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."DEPOSITOS" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_MEDIO_PAGO" NUMBER(22,0), 
	"ID_CUENTA" NUMBER(22,0), 
	"FECHA_DEPOSITO" TIMESTAMP (6), 
	"VALOR" NUMBER(22,0), 
	"ESTADO" VARCHAR2(1 BYTE), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table DETALLE_APUESTA
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."DETALLE_APUESTA" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_APUESTA" NUMBER(22,0), 
	"ID_TIPO_APUESTA" NUMBER(22,0), 
	"ID_ESTADO_APUESTA" NUMBER(22,0), 
	"OPCION_EQUIPO1" VARCHAR2(1 BYTE), 
	"OPCION_EQUIPO2" VARCHAR2(1 BYTE), 
	"OPCION_EMPATE" VARCHAR2(1 BYTE), 
	"OPCION_SI" VARCHAR2(1 BYTE), 
	"OPCION_NO" VARCHAR2(1 BYTE), 
	"OPCION_MAS" VARCHAR2(1 BYTE), 
	"OPCION_MENOS" VARCHAR2(1 BYTE), 
	"VALOR_APOSTADO" NUMBER(22,0), 
	"PORCENTAJE_EQUIPO1_APOSTADO" NUMBER(22,0), 
	"PORCENTAJE_EQUIPO2_APOSTADO" NUMBER(22,0), 
	"PORCENTAJE_EMPATE_APOSTADO" NUMBER(22,0), 
	"PORCENTAJE_SI_APOSTADO" NUMBER(22,2), 
	"PORCENTAJE_NO_APOSTADO" NUMBER(22,2), 
	"PORCENTAJE_MAS_APOSTADO" NUMBER(22,2), 
	"PORCENTAJE_MENOS_APOSTADO" NUMBER(22,2), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table EQUIPOS
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."EQUIPOS" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"REGISTRO_ACTIVO" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table ESTADO_APUESTAS
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."ESTADO_APUESTAS" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ESTADO" VARCHAR2(255 BYTE), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table IDENTIFICACION
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."IDENTIFICACION" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TIPO_DOC" VARCHAR2(255 BYTE), 
	"FECHA_EXPEDICION" DATE, 
	"ID_CIUDAD_EXPEDICION" NUMBER(22,0), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table LEGALES
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."LEGALES" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TERMINOS_CONDICIONES" VARCHAR2(1 BYTE), 
	"AUTORIZACION_RECEPCION_INFO" VARCHAR2(1 BYTE), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table LIMITES_BLOQUEOS
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."LIMITES_BLOQUEOS" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_USUARIO" NUMBER(22,0), 
	"DIARIO" NUMBER(22,0), 
	"SEMANAL" NUMBER(22,0), 
	"MENSUAL" NUMBER(22,0), 
	"TIEMPO_CERRAR_SESION" NUMBER(22,0), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table MEDIO_PAGO
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."MEDIO_PAGO" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"VALOR_MAXIMO" NUMBER(22,0), 
	"VALOR_MINMO" NUMBER(22,0), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table PAISES
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."PAISES" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"PREFIJO_PAIS" VARCHAR2(255 BYTE), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table PREFERENCIAS
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."PREFERENCIAS" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDIOMA_CORREO" VARCHAR2(255 BYTE), 
	"BOLETIN_INFORMATIVO" VARCHAR2(1 BYTE), 
	"CORREO_APUESTAS_DEPORTE" VARCHAR2(1 BYTE), 
	"ENVIO_SMS" VARCHAR2(1 BYTE), 
	"NOTIFICACIONES_NAVEGADOR" VARCHAR2(1 BYTE), 
	"AVISO_BOLETO_APUESTA" VARCHAR2(1 BYTE), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table RETIROS
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."RETIROS" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_CUENTA" NUMBER(22,0), 
	"FECHA_SOLICITUD" TIMESTAMP (6), 
	"FECHA_DESEMBOLSO" DATE, 
	"ID_BANCO" NUMBER(22,0), 
	"ESTADO" VARCHAR2(255 BYTE), 
	"VALIDACION_DOCUMENTOS" VARCHAR2(1 BYTE), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table TIPOS_APUESTAS
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."TIPOS_APUESTAS" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_CRONOGRAMA" NUMBER(22,0), 
	"TIPO_APUESTA" VARCHAR2(255 BYTE), 
	"PORCENTAJE_EQUIPO1" NUMBER(22,2), 
	"PORCENTAJE_EQUIPO2" NUMBER(22,2), 
	"PORCENTAJE_EMPATE" NUMBER(22,2), 
	"PORCENTAJE_SI" NUMBER(22,2), 
	"PORCENTAJE_NO" NUMBER(22,2), 
	"PORCENTAJE_MAS" NUMBER(22,2), 
	"PORCENTAJE_MENOS" NUMBER(22,2), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "DBA_ADMIN"."USUARIOS" SHARING=METADATA 
   (	"ID" NUMBER(22,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE1" VARCHAR2(255 BYTE), 
	"NOMBRE2" VARCHAR2(255 BYTE), 
	"APELLIDO1" VARCHAR2(255 BYTE), 
	"APELLIDO2" VARCHAR2(255 BYTE), 
	"ID_IDENTIFICACION" NUMBER(22,0), 
	"NACIONALIDAD" VARCHAR2(255 BYTE), 
	"ID_CUENTA" NUMBER(22,0), 
	"FECHA_NACIMIENTO" DATE, 
	"VALOR" NUMBER(22,0), 
	"DIRECCION" VARCHAR2(255 BYTE), 
	"CORREO" VARCHAR2(255 BYTE), 
	"CONTRASEÑA" VARCHAR2(255 BYTE), 
	"ID_CIUDAD_RESIDENCIA" NUMBER(22,0), 
	"CELULAR" VARCHAR2(255 BYTE), 
	"DIRECCION2" VARCHAR2(255 BYTE), 
	"ZONA_HORARIA" VARCHAR2(255 BYTE), 
	"ID_PREFERENCIAS" NUMBER(22,0), 
	"LUGAR_NACIMIENTO" VARCHAR2(255 BYTE), 
	"TITULO" VARCHAR2(255 BYTE), 
	"ID_LEGALES" NUMBER(22,0), 
	"REGISTRO_ACTIVO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
REM INSERTING into DBA_ADMIN.APUESTAS
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.AUDITORIA
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.BANCOS
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.BONOS
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.CIUDADES
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.COMPROBANTES_DOCUMENTOS
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.CRONOGRAMA_PARTIDOS
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.CUENTAS
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.DEPARTAMENTOS
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.DEPOSITOS
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.DETALLE_APUESTA
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.EQUIPOS
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.ESTADO_APUESTAS
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.IDENTIFICACION
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.LEGALES
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.LIMITES_BLOQUEOS
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.MEDIO_PAGO
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.PAISES
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.PREFERENCIAS
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.RETIROS
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.TIPOS_APUESTAS
SET DEFINE OFF;
REM INSERTING into DBA_ADMIN.USUARIOS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C009744
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009744" ON "DBA_ADMIN"."APUESTAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009731
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009731" ON "DBA_ADMIN"."AUDITORIA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_AUDITING" ;
--------------------------------------------------------
--  DDL for Index SYS_C009682
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009682" ON "DBA_ADMIN"."BANCOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009834
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009834" ON "DBA_ADMIN"."BONOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009816
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009816" ON "DBA_ADMIN"."CIUDADES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009692
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009692" ON "DBA_ADMIN"."COMPROBANTES_DOCUMENTOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009671
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009671" ON "DBA_ADMIN"."CRONOGRAMA_PARTIDOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index FK_USUARIO_UNICO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."FK_USUARIO_UNICO" ON "DBA_ADMIN"."CUENTAS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009795
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009795" ON "DBA_ADMIN"."CUENTAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009822
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009822" ON "DBA_ADMIN"."DEPARTAMENTOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009768
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009768" ON "DBA_ADMIN"."DEPOSITOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009704
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009704" ON "DBA_ADMIN"."DETALLE_APUESTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009663
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009663" ON "DBA_ADMIN"."EQUIPOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009736
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009736" ON "DBA_ADMIN"."ESTADO_APUESTAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009809
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009809" ON "DBA_ADMIN"."IDENTIFICACION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009849
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009849" ON "DBA_ADMIN"."LEGALES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009843
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009843" ON "DBA_ADMIN"."LIMITES_BLOQUEOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009802
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009802" ON "DBA_ADMIN"."MEDIO_PAGO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009828
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009828" ON "DBA_ADMIN"."PAISES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009754
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009754" ON "DBA_ADMIN"."PREFERENCIAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009720
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009720" ON "DBA_ADMIN"."RETIROS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009677
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009677" ON "DBA_ADMIN"."TIPOS_APUESTAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index FK_IDENTIFICACION_UNICA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."FK_IDENTIFICACION_UNICA" ON "DBA_ADMIN"."USUARIOS" ("ID_IDENTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index FK_PREFERENCIA_UNICA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."FK_PREFERENCIA_UNICA" ON "DBA_ADMIN"."USUARIOS" ("ID_PREFERENCIAS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index FK_CIUDAD_RESIDENCIA_UNICA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."FK_CIUDAD_RESIDENCIA_UNICA" ON "DBA_ADMIN"."USUARIOS" ("ID_CIUDAD_RESIDENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index FK_LEGALES_UNICO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."FK_LEGALES_UNICO" ON "DBA_ADMIN"."USUARIOS" ("ID_LEGALES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009789
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBA_ADMIN"."SYS_C009789" ON "DBA_ADMIN"."USUARIOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  Constraints for Table APUESTAS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."APUESTAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."APUESTAS" MODIFY ("FECHA_APUESTA" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."APUESTAS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."APUESTAS" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."APUESTAS" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."APUESTAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."APUESTAS" ADD CONSTRAINT "CK_APUESTAS_REGISTRO_ACTIVO" CHECK (registro_activo IN ('Y','N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table AUDITORIA
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."AUDITORIA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."AUDITORIA" MODIFY ("FECHA_HORA" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."AUDITORIA" MODIFY ("TABLA" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."AUDITORIA" MODIFY ("RECORD_ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."AUDITORIA" MODIFY ("ACTION" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."AUDITORIA" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."AUDITORIA" MODIFY ("IP" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."AUDITORIA" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."AUDITORIA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_AUDITING"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."AUDITORIA" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_AUDITORIA" CHECK (registro_activo IN ('Y','N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table BANCOS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."BANCOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."BANCOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."BANCOS" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."BANCOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."BANCOS" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_BANCOS" CHECK (registro_activo IN ('Y','N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table BONOS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."BONOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."BONOS" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."BONOS" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."BONOS" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."BONOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."BONOS" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_BONO" CHECK (registro_activo IN ('Y','N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table CIUDADES
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."CIUDADES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."CIUDADES" MODIFY ("ID_DEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."CIUDADES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."CIUDADES" MODIFY ("CODIGO_ZIP" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."CIUDADES" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."CIUDADES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."CIUDADES" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_CIUDADES" CHECK (registro_activo IN ('Y','N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPROBANTES_DOCUMENTOS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."COMPROBANTES_DOCUMENTOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."COMPROBANTES_DOCUMENTOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."COMPROBANTES_DOCUMENTOS" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."COMPROBANTES_DOCUMENTOS" MODIFY ("TAMAÑO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."COMPROBANTES_DOCUMENTOS" MODIFY ("EXTENSION" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."COMPROBANTES_DOCUMENTOS" MODIFY ("URL" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."COMPROBANTES_DOCUMENTOS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."COMPROBANTES_DOCUMENTOS" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."COMPROBANTES_DOCUMENTOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."COMPROBANTES_DOCUMENTOS" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_COMPROBANTES" CHECK (registro_activo IN ('Y','N')) ENABLE;
  ALTER TABLE "DBA_ADMIN"."COMPROBANTES_DOCUMENTOS" ADD CONSTRAINT "CK_OPCIONES_ESTADO_COMPROBANTES" CHECK (estado IN ('PENDIENTE', 'EN PROCESO', 'RECHAZADA', 'EXITOSO')) ENABLE;
--------------------------------------------------------
--  Constraints for Table CRONOGRAMA_PARTIDOS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."CRONOGRAMA_PARTIDOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."CRONOGRAMA_PARTIDOS" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."CRONOGRAMA_PARTIDOS" MODIFY ("HORA" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."CRONOGRAMA_PARTIDOS" MODIFY ("ID_EQUIPO1" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."CRONOGRAMA_PARTIDOS" MODIFY ("ID_EQUIPO2" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."CRONOGRAMA_PARTIDOS" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."CRONOGRAMA_PARTIDOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."CRONOGRAMA_PARTIDOS" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_CRONOGRAMA" CHECK (registro_activo IN ('Y','N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table CUENTAS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."CUENTAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."CUENTAS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."CUENTAS" MODIFY ("SALDO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."CUENTAS" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."CUENTAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."CUENTAS" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_CUENTAS" CHECK (registro_activo IN ('Y','N')) ENABLE;
  ALTER TABLE "DBA_ADMIN"."CUENTAS" ADD CONSTRAINT "FK_USUARIO_UNICO" UNIQUE ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTAMENTOS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."DEPARTAMENTOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."DEPARTAMENTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."DEPARTAMENTOS" MODIFY ("ID_PAIS" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."DEPARTAMENTOS" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."DEPARTAMENTOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."DEPARTAMENTOS" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_DEPARTAMENTOS" CHECK (registro_activo IN ('Y','N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPOSITOS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."DEPOSITOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."DEPOSITOS" MODIFY ("ID_MEDIO_PAGO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."DEPOSITOS" MODIFY ("ID_CUENTA" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."DEPOSITOS" MODIFY ("FECHA_DEPOSITO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."DEPOSITOS" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."DEPOSITOS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."DEPOSITOS" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."DEPOSITOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."DEPOSITOS" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_DEPOSITOS" CHECK (registro_activo IN ('Y','N')) ENABLE;
  ALTER TABLE "DBA_ADMIN"."DEPOSITOS" ADD CONSTRAINT "CK_OPCIONES_ESTADO_DEPOSITOS" CHECK (estado IN ('PENDIENTE', 'EN PROCESO', 'RECHAZADA', 'EXITOSO')) ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLE_APUESTA
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" MODIFY ("OPCION_EQUIPO1" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" MODIFY ("OPCION_EQUIPO2" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" MODIFY ("OPCION_EMPATE" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" MODIFY ("OPCION_SI" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" MODIFY ("OPCION_NO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" MODIFY ("OPCION_MAS" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" MODIFY ("OPCION_MENOS" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_DETALLE_APUESTA" CHECK (registro_activo IN ('Y','N')) ENABLE;
  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" ADD CONSTRAINT "CK_OPCIONES_ESTADO_DETALLE_APUESTA1" CHECK (opcion_equipo1 IN ('Y', 'N')) ENABLE;
  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" ADD CONSTRAINT "CK_OPCIONES_ESTADO_DETALLE_APUESTA2" CHECK (opcion_equipo2 IN ('Y', 'N')) ENABLE;
  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" ADD CONSTRAINT "CK_OPCIONES_ESTADO_DETALLE_APUESTA3" CHECK (opcion_empate IN ('Y', 'N')) ENABLE;
  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" ADD CONSTRAINT "CK_OPCIONES_ESTADO_DETALLE_APUESTA4" CHECK (opcion_si IN ('Y', 'N')) ENABLE;
  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" ADD CONSTRAINT "CK_OPCIONES_ESTADO_DETALLE_APUESTA5" CHECK (opcion_no IN ('Y', 'N')) ENABLE;
  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" ADD CONSTRAINT "CK_OPCIONES_ESTADO_DETALLE_APUESTA6" CHECK (opcion_mas IN ('Y', 'N')) ENABLE;
  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" ADD CONSTRAINT "CK_OPCIONES_ESTADO_DETALLE_APUESTA7" CHECK (opcion_menos IN ('Y', 'N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table EQUIPOS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."EQUIPOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."EQUIPOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."EQUIPOS" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."EQUIPOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."EQUIPOS" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_EQUIPOS" CHECK (registro_activo IN ('Y','N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTADO_APUESTAS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."ESTADO_APUESTAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."ESTADO_APUESTAS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."ESTADO_APUESTAS" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."ESTADO_APUESTAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."ESTADO_APUESTAS" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_ESTADO_APUESTAS" CHECK (registro_activo IN ('Y','N')) ENABLE;
  ALTER TABLE "DBA_ADMIN"."ESTADO_APUESTAS" ADD CONSTRAINT "CK_ESTADO_APUESTAS" CHECK (estado IN ('Abierta','Ganada','Perdida','vendida','Cancelada','Reembolsada','Invalida','Rechazado','Pedido','Parte aprobada')) ENABLE;
--------------------------------------------------------
--  Constraints for Table IDENTIFICACION
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."IDENTIFICACION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."IDENTIFICACION" MODIFY ("TIPO_DOC" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."IDENTIFICACION" MODIFY ("FECHA_EXPEDICION" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."IDENTIFICACION" MODIFY ("ID_CIUDAD_EXPEDICION" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."IDENTIFICACION" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."IDENTIFICACION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."IDENTIFICACION" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_IDENTIFICACION" CHECK (registro_activo IN ('Y','N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table LEGALES
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."LEGALES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."LEGALES" MODIFY ("TERMINOS_CONDICIONES" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."LEGALES" MODIFY ("AUTORIZACION_RECEPCION_INFO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."LEGALES" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."LEGALES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."LEGALES" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_LEGALES" CHECK (registro_activo IN ('Y','N')) ENABLE;
  ALTER TABLE "DBA_ADMIN"."LEGALES" ADD CONSTRAINT "CK_TERMINOS_LIMITES_LEGALES" CHECK (terminos_condiciones IN ('Y','N')) ENABLE;
  ALTER TABLE "DBA_ADMIN"."LEGALES" ADD CONSTRAINT "CK_RECEPCIO_INFO_LIMITES_LEGALES" CHECK (autorizacion_recepcion_info IN ('Y','N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table LIMITES_BLOQUEOS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."LIMITES_BLOQUEOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."LIMITES_BLOQUEOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."LIMITES_BLOQUEOS" MODIFY ("DIARIO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."LIMITES_BLOQUEOS" MODIFY ("SEMANAL" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."LIMITES_BLOQUEOS" MODIFY ("MENSUAL" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."LIMITES_BLOQUEOS" MODIFY ("TIEMPO_CERRAR_SESION" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."LIMITES_BLOQUEOS" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."LIMITES_BLOQUEOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."LIMITES_BLOQUEOS" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_LIMITES_BLOQUEOS" CHECK (registro_activo IN ('Y','N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table MEDIO_PAGO
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."MEDIO_PAGO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."MEDIO_PAGO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."MEDIO_PAGO" MODIFY ("VALOR_MAXIMO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."MEDIO_PAGO" MODIFY ("VALOR_MINMO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."MEDIO_PAGO" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."MEDIO_PAGO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."MEDIO_PAGO" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_MEDIO_PAGO" CHECK (registro_activo IN ('Y','N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table PAISES
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."PAISES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."PAISES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."PAISES" MODIFY ("PREFIJO_PAIS" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."PAISES" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."PAISES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."PAISES" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_PAIS" CHECK (registro_activo IN ('Y','N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table PREFERENCIAS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."PREFERENCIAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."PREFERENCIAS" MODIFY ("IDIOMA_CORREO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."PREFERENCIAS" MODIFY ("BOLETIN_INFORMATIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."PREFERENCIAS" MODIFY ("CORREO_APUESTAS_DEPORTE" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."PREFERENCIAS" MODIFY ("ENVIO_SMS" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."PREFERENCIAS" MODIFY ("NOTIFICACIONES_NAVEGADOR" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."PREFERENCIAS" MODIFY ("AVISO_BOLETO_APUESTA" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."PREFERENCIAS" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."PREFERENCIAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."PREFERENCIAS" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_PREFERENCIAS" CHECK (registro_activo IN ('Y','N')) ENABLE;
  ALTER TABLE "DBA_ADMIN"."PREFERENCIAS" ADD CONSTRAINT "CK_BOLETIN_PREFERENCIAS" CHECK (boletin_informativo IN ('Y','N')) ENABLE;
  ALTER TABLE "DBA_ADMIN"."PREFERENCIAS" ADD CONSTRAINT "CK_CORREO_DEPORTE_PREFERENCIAS" CHECK (correo_apuestas_deporte IN ('Y','N')) ENABLE;
  ALTER TABLE "DBA_ADMIN"."PREFERENCIAS" ADD CONSTRAINT "CK_ENVIO_SMS_PREFERENCIAS" CHECK (envio_sms IN ('Y','N')) ENABLE;
  ALTER TABLE "DBA_ADMIN"."PREFERENCIAS" ADD CONSTRAINT "CK_NOTIFICACION_PREFERENCIAS" CHECK (notificaciones_navegador IN ('Y','N')) ENABLE;
  ALTER TABLE "DBA_ADMIN"."PREFERENCIAS" ADD CONSTRAINT "CK_AVISO_PREFERENCIAS" CHECK (aviso_boleto_apuesta IN ('Y','N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table RETIROS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."RETIROS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."RETIROS" MODIFY ("ID_CUENTA" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."RETIROS" MODIFY ("FECHA_SOLICITUD" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."RETIROS" MODIFY ("ID_BANCO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."RETIROS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."RETIROS" MODIFY ("VALIDACION_DOCUMENTOS" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."RETIROS" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."RETIROS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."RETIROS" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_RETIROS" CHECK (registro_activo IN ('Y','N')) ENABLE;
  ALTER TABLE "DBA_ADMIN"."RETIROS" ADD CONSTRAINT "CK_OPCIONES_ESTADO_RETIROS" CHECK (estado IN ('PENDIENTE', 'EN PROCESO', 'RECHAZADA', 'EXITOSO')) ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPOS_APUESTAS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."TIPOS_APUESTAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."TIPOS_APUESTAS" MODIFY ("ID_CRONOGRAMA" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."TIPOS_APUESTAS" MODIFY ("TIPO_APUESTA" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."TIPOS_APUESTAS" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."TIPOS_APUESTAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."TIPOS_APUESTAS" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_TIPOS_APUESTAS" CHECK (registro_activo IN ('Y','N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."USUARIOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."USUARIOS" MODIFY ("NOMBRE1" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."USUARIOS" MODIFY ("APELLIDO1" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."USUARIOS" MODIFY ("ID_IDENTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."USUARIOS" MODIFY ("NACIONALIDAD" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."USUARIOS" MODIFY ("ID_CUENTA" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."USUARIOS" MODIFY ("FECHA_NACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."USUARIOS" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."USUARIOS" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."USUARIOS" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."USUARIOS" MODIFY ("CONTRASEÑA" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."USUARIOS" MODIFY ("ID_CIUDAD_RESIDENCIA" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."USUARIOS" MODIFY ("CELULAR" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."USUARIOS" MODIFY ("ID_PREFERENCIAS" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."USUARIOS" MODIFY ("LUGAR_NACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."USUARIOS" MODIFY ("TITULO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."USUARIOS" MODIFY ("ID_LEGALES" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."USUARIOS" MODIFY ("REGISTRO_ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "DBA_ADMIN"."USUARIOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."USUARIOS" ADD CONSTRAINT "CK_REGISTRO_ACTIVO_USUARIOS" CHECK (registro_activo IN ('Y','N')) ENABLE;
  ALTER TABLE "DBA_ADMIN"."USUARIOS" ADD CONSTRAINT "FK_IDENTIFICACION_UNICA" UNIQUE ("ID_IDENTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."USUARIOS" ADD CONSTRAINT "FK_PREFERENCIA_UNICA" UNIQUE ("ID_PREFERENCIAS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."USUARIOS" ADD CONSTRAINT "FK_CIUDAD_RESIDENCIA_UNICA" UNIQUE ("ID_CIUDAD_RESIDENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "DBA_ADMIN"."USUARIOS" ADD CONSTRAINT "FK_LEGALES_UNICO" UNIQUE ("ID_LEGALES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APUESTAS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."APUESTAS" ADD CONSTRAINT "FK_USUARIO_APUESTAS" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "DBA_ADMIN"."USUARIOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CIUDADES
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."CIUDADES" ADD CONSTRAINT "FK_DEPARTAMENTOS" FOREIGN KEY ("ID_DEPARTAMENTO")
	  REFERENCES "DBA_ADMIN"."DEPARTAMENTOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPROBANTES_DOCUMENTOS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."COMPROBANTES_DOCUMENTOS" ADD CONSTRAINT "FK_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "DBA_ADMIN"."USUARIOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CRONOGRAMA_PARTIDOS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."CRONOGRAMA_PARTIDOS" ADD CONSTRAINT "FK_EQUIPO1" FOREIGN KEY ("ID_EQUIPO1")
	  REFERENCES "DBA_ADMIN"."EQUIPOS" ("ID") ENABLE;
  ALTER TABLE "DBA_ADMIN"."CRONOGRAMA_PARTIDOS" ADD CONSTRAINT "FK_EQUIPO2" FOREIGN KEY ("ID_EQUIPO2")
	  REFERENCES "DBA_ADMIN"."EQUIPOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUENTAS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."CUENTAS" ADD CONSTRAINT "FK_USUARIOS" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "DBA_ADMIN"."USUARIOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPARTAMENTOS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."DEPARTAMENTOS" ADD CONSTRAINT "FK_PAISES" FOREIGN KEY ("ID_PAIS")
	  REFERENCES "DBA_ADMIN"."PAISES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPOSITOS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."DEPOSITOS" ADD CONSTRAINT "FK_MEDIO_PAGO" FOREIGN KEY ("ID_MEDIO_PAGO")
	  REFERENCES "DBA_ADMIN"."MEDIO_PAGO" ("ID") ENABLE;
  ALTER TABLE "DBA_ADMIN"."DEPOSITOS" ADD CONSTRAINT "FK_CUENTA" FOREIGN KEY ("ID_CUENTA")
	  REFERENCES "DBA_ADMIN"."CUENTAS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_APUESTA
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" ADD CONSTRAINT "FK_APUESTA" FOREIGN KEY ("ID_APUESTA")
	  REFERENCES "DBA_ADMIN"."APUESTAS" ("ID") ENABLE;
  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" ADD CONSTRAINT "FK_ESTADO_APUESTA" FOREIGN KEY ("ID_ESTADO_APUESTA")
	  REFERENCES "DBA_ADMIN"."ESTADO_APUESTAS" ("ID") ENABLE;
  ALTER TABLE "DBA_ADMIN"."DETALLE_APUESTA" ADD CONSTRAINT "FK_TIPO_APUESTA" FOREIGN KEY ("ID_TIPO_APUESTA")
	  REFERENCES "DBA_ADMIN"."TIPOS_APUESTAS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IDENTIFICACION
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."IDENTIFICACION" ADD CONSTRAINT "FK_CIUDAD_EXPEDICION" FOREIGN KEY ("ID_CIUDAD_EXPEDICION")
	  REFERENCES "DBA_ADMIN"."CIUDADES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIMITES_BLOQUEOS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."LIMITES_BLOQUEOS" ADD CONSTRAINT "FK_USUARIO_BLOQUEOS" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "DBA_ADMIN"."USUARIOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RETIROS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."RETIROS" ADD CONSTRAINT "FK_BANCO" FOREIGN KEY ("ID_BANCO")
	  REFERENCES "DBA_ADMIN"."BANCOS" ("ID") ENABLE;
  ALTER TABLE "DBA_ADMIN"."RETIROS" ADD CONSTRAINT "FK_CUENTA_RETIROS" FOREIGN KEY ("ID_CUENTA")
	  REFERENCES "DBA_ADMIN"."CUENTAS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TIPOS_APUESTAS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."TIPOS_APUESTAS" ADD CONSTRAINT "FK_CRONOGRAMA" FOREIGN KEY ("ID_CRONOGRAMA")
	  REFERENCES "DBA_ADMIN"."CRONOGRAMA_PARTIDOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "DBA_ADMIN"."USUARIOS" ADD CONSTRAINT "FK_IDENTIFICACION" FOREIGN KEY ("ID_IDENTIFICACION")
	  REFERENCES "DBA_ADMIN"."IDENTIFICACION" ("ID") ENABLE;
  ALTER TABLE "DBA_ADMIN"."USUARIOS" ADD CONSTRAINT "FK_PREPRERENCIAS" FOREIGN KEY ("ID_PREFERENCIAS")
	  REFERENCES "DBA_ADMIN"."PREFERENCIAS" ("ID") ENABLE;
  ALTER TABLE "DBA_ADMIN"."USUARIOS" ADD CONSTRAINT "FK_CIUDAD_RESIDENCIA" FOREIGN KEY ("ID_CIUDAD_RESIDENCIA")
	  REFERENCES "DBA_ADMIN"."CIUDADES" ("ID") ENABLE;
  ALTER TABLE "DBA_ADMIN"."USUARIOS" ADD CONSTRAINT "FK_LEGALES" FOREIGN KEY ("ID_LEGALES")
	  REFERENCES "DBA_ADMIN"."LEGALES" ("ID") ENABLE;
