--select * from bonos;
/* INSERTAMOS DATOS EN LA TABLA BONOS,  PARA HABILITAR BONOS DE 10000 peso hasta 50000*/
insert into BONOS (codigo, valor, registro_activo) values ('rSI8n', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('fEo9F', 50000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('Y6UTA', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('oEc64', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('N7oGm', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('Sdk4x', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('Gvqdu', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('Niu1U', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('W8JZY', 10000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('Xx5uE', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('lBGSO', 50000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('ZCZ1h', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('EimsW', 50000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('NLPlR', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('1UkQj', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('Sufqb', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('rDUds', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('WP8Wb', 50000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('zFMRp', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('2Rfog', 10000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('JXitf', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('bZcJp', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('5a0tx', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('sfs0u', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('qHqTD', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('QOmbk', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('chL5K', 10000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('tyZee', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('CL6cn', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('YU821', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('dIzsk', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('smltP', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('91VPZ', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('cOBQY', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('dnUTZ', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('A2AfB', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('2ozRm', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('kqioP', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('xFHiK', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('ufO02', 50000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('yoyCm', 10000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('OCXOc', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('GKLDJ', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('grplC', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('E3e95', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('bZato', 50000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('tfIuO', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('n1SFo', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('hoL0w', 10000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('OMNA5', 50000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('FcgoI', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('uvN3y', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('kKtAl', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('X7ucv', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('pwXuy', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('kzSaX', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('4kiFC', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('Rds4H', 10000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('XuBC4', 50000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('9PolY', 10000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('Wur9q', 50000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('6LtMc', 50000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('Tu1qN', 10000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('vUY8u', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('wy4OG', 50000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('m76kv', 50000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('DH2PW', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('7CBG9', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('25gCY', 10000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('fTYcT', 10000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('AFSKt', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('URQ8r', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('LQJOi', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('ZzN4x', 10000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('SuKE4', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('QPQ1g', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('AV0Gp', 10000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('2Kbf7', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('lH2tZ', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('sM3yJ', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('o5Smz', 10000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('iNw7f', 50000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('H9vtq', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('dSdh5', 10000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('le02P', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('wqenk', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('sJj6i', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('m5TLv', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('Gn7Vt', 50000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('KsIL3', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('4HiVh', 50000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('6fOga', 30000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('UMSw1', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('oYcCf', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('DAOBS', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('35WAR', 40000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('1d2dl', 10000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('236XX', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('wxMY1', 20000, 'Y');
insert into BONOS (codigo, valor, registro_activo) values ('XrJq2', 30000, 'Y');


/* INSERTAMOS EL PAIS COLOMBIA */
insert into PAISES (nombre, prefijo_pais, registro_activo) values ('Colombia', 'CO', 'Y');
SELECT * FROM PAISES;
/* INSERTAMOS LOS DEPARTAMENTOS DE COLOMBIA */
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('ANTIOQUIA',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('ATLANTICO',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('BOLIVAR',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('BOYACA',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('CALDAS',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('CAQUETA',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('CAUCA',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('CESAR',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('CORDOBA',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('CUNDINAMARCA',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('CHOCO',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('HUILA',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('LA GUAJIRA',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('MAGDALENA',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('META',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('NARIÑO',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('NORTE SANTANDER',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('QUINDIO',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('RISARALDA',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('SANTANDER',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('SUCRE',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('TOLIMA',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('VALLE',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('ARAUCA',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('CASANARE',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('PUTUMAYO',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('SAN ANDRES',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('AMAZONAS',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('GUAINIA',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('GUAVIARE',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('VAUPES',1, 'Y');
insert into DEPARTAMENTOS (nombre, id_pais, registro_activo) values ('VICHADA',1, 'Y');

/* CIUDADES DE ANTIOQUIA */

INSERT INTO CIUDADES (id_departamento, nombre, codigo_zip,registro_activo) values (1,);