--INSERTAR MAS DATOS


--PREFERENCIAS
INSERT INTO preferencias (id_usuario,nombre,idioma_correo,boletin_informativo,correo_apuesta_deporte,envio_sms,notificaciones_navegador,aviso_boleta_apuesta,registro_activo) VALUES (1,'Zenaida, Jeanette, Arthur, Signe','aleman','bienvenido alas apuestas','odio.semper@elit.net','N','N','N','Y');
INSERT INTO preferencias (id_usuario,nombre,idioma_correo,boletin_informativo,correo_apuesta_deporte,envio_sms,notificaciones_navegador,aviso_boleta_apuesta,registro_activo) VALUES (2,'Scarlet, Lysandra, Kato, Rebecca','español','bienvenido alas apuestas','netus.et@In.edu','Y','Y','Y','Y');
INSERT INTO preferencias (id_usuario,nombre,idioma_correo,boletin_informativo,correo_apuesta_deporte,envio_sms,notificaciones_navegador,aviso_boleta_apuesta,registro_activo) VALUES (3,'Iola, Channing, Wyatt, Drake','english','bienvenido alas apuestas','enim@eu.ca','Y','Y','Y','Y');
INSERT INTO preferencias (id_usuario,nombre,idioma_correo,boletin_informativo,correo_apuesta_deporte,envio_sms,notificaciones_navegador,aviso_boleta_apuesta,registro_activo) VALUES (4,'Gloria, Casey, Carla, Ali','aleman','bienvenido alas apuestas','ipsum.Curabitur.consequat@Vivamussit.com','Y','N','N','Y');
INSERT INTO preferencias (id_usuario,nombre,idioma_correo,boletin_informativo,correo_apuesta_deporte,envio_sms,notificaciones_navegador,aviso_boleta_apuesta,registro_activo) VALUES (5,'Flynn, Herrod, Ruth, Sacha','english','bienvenido alas apuestas','lobortis.mauris@sociisnatoquepenatibus.edu','N','Y','N','Y');

--cronograma_partido
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 18:28:13',15,19,'Mr.',4,2,'','',4,3,'abierto','N');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 00:49:04',27,24,'Mrs.',5,4,'','Mr.',9,1,'cerrado','Y');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 12:23:16',1,11,'Mr.',1,5,'Mrs.','Mr.',9,2,'abierto','N');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 20:15:58',3,10,'Dr.',4,3,'Mrs.','Dr.',2,6,'cerrado','Y');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 09:06:15',25,24,'Ms.',3,3,'Dr.','Mrs.',6,4,'cerrado','Y');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 14:55:02',12,28,'Mr.',5,5,'Dr.','Dr.',1,7,'abierto','N');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 23:38:58',22,19,'Mr.',2,2,'Dr.','Ms.',10,1,'abierto','');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 13:26:07',3,12,'',3,3,'Mrs.','Dr.',1,5,'cerrado','Y');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 22:38:04',8,19,'Mr.',2,4,'Dr.','Mrs.',5,4,'cerrado','');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 10:02:58',8,15,'Dr.',3,3,'Mr.','Dr.',2,5,'cerrado','N');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 21:58:41',15,13,'',3,2,'Dr.','Mr.',1,4,'cerrado','N');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 11:25:29',12,28,'Mrs.',5,3,'Dr.','Mrs.',6,5,'abierto','');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 14:31:46',15,10,'Ms.',1,1,'Ms.','',5,3,'cerrado','Y');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 00:01:49',18,25,'Dr.',1,4,'Ms.','Mr.',9,2,'cerrado','N');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 06:01:58',24,5,'',4,1,'Mrs.','Dr.',9,8,'abierto','Y');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 20:28:11',17,13,'Mrs.',5,5,'Mr.','Ms.',2,9,'cerrado','Y');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 00:28:57',4,27,'Dr.',2,4,'Dr.','',8,2,'cerrado','');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 05:28:33',20,19,'Mrs.',5,4,'Mr.','',2,6,'abierto','N');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 09:44:03',10,18,'',4,3,'','Ms.',3,6,'cerrado','N');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 05:03:11',11,13,'Mrs.',5,5,'','Mr.',10,2,'abierto','N');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 11:57:46',11,6,'Mr.',5,2,'Mrs.','',8,6,'cerrado','N');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 02:23:16',5,16,'Dr.',3,4,'','Ms.',3,9,'abierto','');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 22:40:35',11,17,'Mrs.',1,3,'','Mr.',8,4,'cerrado','');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 05:25:33',8,18,'Mrs.',5,2,'Mr.','',9,8,'abierto','Y');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 17:46:04',14,14,'Ms.',2,1,'Dr.','Dr.',2,5,'cerrado','N');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 00:01:51',12,10,'Mr.',2,4,'Dr.','Mrs.',5,10,'abierto','N');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 19:14:57',19,28,'Mrs.',1,3,'Mrs.','Dr.',10,1,'cerrado','N');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 23:42:00',27,23,'',3,1,'','Mr.',1,2,'cerrado','N');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 05:48:03',3,10,'Ms.',1,1,'','Mrs.',4,9,'abierto','Y');
INSERT INTO cronograma_partido (fecha,hora,id_equipo1,id_equipo2,ganador,goles_equipo1,goles_equipo2,ganador_tiempo1,ganador_tiempo2,goles_tiempo1,goles_tiempo2,estado,registro_activo) VALUES ('11/16/2018',' 20:08:16',23,9,'Ms.',2,3,'','Dr.',3,8,'abierto','');