--CREATE OR REPLACE FUNCTION F_Validar_Movimiento(id_cliente number, saldo number, movimiento number) return VARCHAR
--IS


set serveroutput on
DECLARE
id_cliente number;
saldo number;
movimiento number;
CANTIDAD_DOCUMENTOS NUMBER;
SALDO_ACTUAL NUMBER;
BANCO NUMBER;
MENSAJE VARCHAR(255);
BEGIN

id_cliente:=1;
saldo:=2000;
movimiento :=1;





CANTIDAD_DOCUMENTOS:=NVL(SELECT COUNT(id)   FROM COMPROBANTES_DOCUMENTOS WHERE ID_USUARIO=id_cliente AND registro_activo='Y' group by TIPO),0);


/*VERIFICA LA CANTIDAD DE DOCUMENTOS SEA IGUAL A 4 QUE SON LOS SIGUIENTES: 

A) Factura servicios públicos con nombre y dirección.
B) Comprobante de Depósito
C) Identificación con nombre y fecha de nacimiento
D) Foto personal sosteniendo su documento de identificación legible.

SI NO LOS TIENE RETORNA 1
*/
IF CANTIDAD_DOCUMENTOS<4 THEN
 
-- RETURN 'NOMBRE CON LA DOCUMENTACION REQUERIDA PARA REALIZAR OPERACION';

MENSAJE:='NOMBRE CON LA DOCUMENTACION REQUERIDA PARA REALIZAR OPERACION';
DBMS_OUTPUT.PUT_LINE(MENSAJE);

END IF;

BANCO=SELECT NVL(COUNT(id),0)   FROM BANCOVSUSUARIOS WHERE ID_USUARIO=id_cliente AND registro_activo='Y';


/*VERIFICA LA CANTIDAD DE BANCOS QUE TIENE UN USUARIO Y TIPO MOVIMIENTO, SI NO LO TIENE 

TIPOS MOVIMIENTOS
1: RETIRO
2: DEPOSITO

RETORNA 2
*/
IF BANCO>0 AND movimiento=1  THEN
 
-- RETURN 'NO TIENE NINGUN BANCO REGISTRADO EN EL SISTEMA';

MENSAJE:='NO TIENE NINGUN BANCO REGISTRADO EN EL SISTEMA';
DBMS_OUTPUT.PUT_LINE(MENSAJE);

END IF;


SELECT NVL(SALDO,0) INTO SALDO_ACTUAL FROM USUARIOS WHERE ID=id_cliente AND registro_activo='Y';


/*VERIFICA EL SALDO ACTUAL SI ES NEGATIVO 
RETORNA 3  
*/
IF (saldo_actual-saldo)<0 THEN
 
-- RETURN 'SALDO INSUFICIENTE PARA REALIZAR LA OPERACION';

MENSAJE:='SALDO INSUFICIENTE PARA REALIZAR LA OPERACION';
DBMS_OUTPUT.PUT_LINE(MENSAJE);



END IF;


/*
SI TODO ESTA CORRECTO 
RETORNO 0

*/

--RETURN 'APROBADO';



END ;


SELECT '1',F_Validar_Movimiento(1,20000,1) FROM dual


