/*AUIDOTORIA APUESTAS*/

CREATE OR REPLACE TRIGGER TG_AUDITORIA_APUESTAS
AFTER INSERT OR UPDATE OR DELETE ON APUESTAS
FOR EACH ROW
BEGIN 
	
	IF INSERTING THEN 
	INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,REGISTRO_ACTIVO) VALUES (
   'APUESTAS',:NEW.ID,'INSERCION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');
	
    END IF;
   
   	IF UPDATING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,REGISTRO_ACTIVO) VALUES (
   'APUESTAS',:NEW.ID,'ACTULIZACION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
   	IF DELETING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,REGISTRO_ACTIVO) VALUES (
                             'APUESTAS',:OLD.ID,'BORRADO',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   

END;


/*AUIDOTORIA BONOS*/

CREATE OR REPLACE TRIGGER TG_AUDITORIA_BONOS
AFTER INSERT OR UPDATE OR DELETE ON BONOS
FOR EACH ROW
BEGIN 
	
	IF INSERTING THEN 
	INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'BONOS',:NEW.ID,'INSERCION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');
	
    END IF;
   
   	IF UPDATING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'BONOS',:NEW.ID,'ACTULIZACION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
   	IF DELETING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
                             'BONOS',:OLD.ID,'BORRADO',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
END;


/*AUIDOTORIA BANCOS*/

CREATE OR REPLACE TRIGGER TG_AUDITORIA_BANCOS
AFTER INSERT OR UPDATE OR DELETE ON BANCOS
FOR EACH ROW
BEGIN 
	
	IF INSERTING THEN 
	INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'BANCOS',:NEW.ID,'INSERCION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');
	
    END IF;
   
   	IF UPDATING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'BANCOS',:NEW.ID,'ACTULIZACION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
   	IF DELETING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
                             'BANCOS',:OLD.ID,'BORRADO',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
END;


/*AUIDOTORIA CIUDADES*/

CREATE OR REPLACE TRIGGER TG_AUDITORIA_CIUDADES
AFTER INSERT OR UPDATE OR DELETE ON CIUDADES
FOR EACH ROW
BEGIN 
	
	IF INSERTING THEN 
	INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'CIUDADES',:NEW.ID,'INSERCION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');
	
    END IF;
   
   	IF UPDATING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'CIUDADES',:NEW.ID,'ACTULIZACION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
   	IF DELETING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
                             'CIUDADES',:OLD.ID,'BORRADO',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
END;




/*AUIDOTORIA DOCUMENTOS*/

CREATE OR REPLACE TRIGGER TG_AUDITORIA_COMPROBANTES_DOCUMENTOS
AFTER INSERT OR UPDATE OR DELETE ON COMPROBANTES_DOCUMENTOS
FOR EACH ROW
BEGIN 
	
	IF INSERTING THEN 
	INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'COMPROBANTES_DOCUMENTOS',:NEW.ID,'INSERCION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');
	
    END IF;
   
   	IF UPDATING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'COMPROBANTES_DOCUMENTOS',:NEW.ID,'ACTULIZACION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
   	IF DELETING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
                             'COMPROBANTES_DOCUMENTOS',:OLD.ID,'BORRADO',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
END;



/*AUIDOTORIA CRONOGRAMA_PARTIDOS*/

CREATE OR REPLACE TRIGGER TG_AUDITORIA_CRONOGRAMA_PARTIDOS
AFTER INSERT OR UPDATE OR DELETE ON CRONOGRAMA_PARTIDOS
FOR EACH ROW
BEGIN 
	
	IF INSERTING THEN 
	INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'CRONOGRAMA_PARTIDOS',:NEW.ID,'INSERCION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');
	
    END IF;
   
   	IF UPDATING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'CRONOGRAMA_PARTIDOS',:NEW.ID,'ACTULIZACION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
   	IF DELETING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
                             'CRONOGRAMA_PARTIDOS',:OLD.ID,'BORRADO',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
END;



/*AUIDOTORIA DEPARTAMENTOS*/

CREATE OR REPLACE TRIGGER TG_AUDITORIA_DEPARTAMENTOS
AFTER INSERT OR UPDATE OR DELETE ON DEPARTAMENTOS
FOR EACH ROW
BEGIN 
	
	IF INSERTING THEN 
	INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'DEPARTAMENTOS',:NEW.ID,'INSERCION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');
	
    END IF;
   
   	IF UPDATING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'DEPARTAMENTOS',:NEW.ID,'ACTULIZACION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
   	IF DELETING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
                             'DEPARTAMENTOS',:OLD.ID,'BORRADO',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
END;




/*AUIDOTORIA DEPOSITOS*/

CREATE OR REPLACE TRIGGER TG_AUDITORIA_DEPOSITOS
AFTER INSERT OR UPDATE OR DELETE ON DEPOSITOS
FOR EACH ROW
BEGIN 
	
	IF INSERTING THEN 
	INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'DEPOSITOS',:NEW.ID,'INSERCION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');
	
    END IF;
   
   	IF UPDATING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'DEPOSITOS',:NEW.ID,'ACTULIZACION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
   	IF DELETING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
                             'DEPOSITOS',:OLD.ID,'BORRADO',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
END;




/*AUIDOTORIA APUESTA*/

CREATE OR REPLACE TRIGGER TG_AUDITORIA_DETALLE_APUESTA
AFTER INSERT OR UPDATE OR DELETE ON DETALLE_APUESTA
FOR EACH ROW
BEGIN 
	
	IF INSERTING THEN 
	INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'DETALLE_APUESTA',:NEW.ID,'INSERCION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');
	
    END IF;
   
   	IF UPDATING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'DETALLE_APUESTA',:NEW.ID,'ACTULIZACION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
   	IF DELETING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
                             'DETALLE_APUESTA',:OLD.ID,'BORRADO',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
END;






/*AUIDOTORIA EQUIPOS*/

CREATE OR REPLACE TRIGGER TG_AUDITORIA_EQUIPOS
AFTER INSERT OR UPDATE OR DELETE ON EQUIPOS
FOR EACH ROW
BEGIN 
	
	IF INSERTING THEN 
	INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'EQUIPOS',:NEW.ID,'INSERCION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');
	
    END IF;
   
   	IF UPDATING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'EQUIPOS',:NEW.ID,'ACTULIZACION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
   	IF DELETING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
    'EQUIPOS',:OLD.ID,'BORRADO',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
END;

/*AUIDOTORIA IDENTIFICACION*/

CREATE OR REPLACE TRIGGER TG_AUDITORIA_IDENTIFICACION
AFTER INSERT OR UPDATE OR DELETE ON IDENTIFICACION
FOR EACH ROW
BEGIN 
	
	IF INSERTING THEN 
	INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'IDENTIFICACION',:NEW.ID,'INSERCION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');
	
    END IF;
   
   	IF UPDATING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'IDENTIFICACION',:NEW.ID,'ACTULIZACION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
   	IF DELETING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
    'IDENTIFICACION',:OLD.ID,'BORRADO',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
END;


/*AUIDOTORIA LEGALES*/

CREATE OR REPLACE TRIGGER TG_AUDITORIA_LEGALES
AFTER INSERT OR UPDATE OR DELETE ON LEGALES
FOR EACH ROW
BEGIN 
	
	IF INSERTING THEN 
	INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'LEGALES',:NEW.ID,'INSERCION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');
	
    END IF;
   
   	IF UPDATING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'LEGALES',:NEW.ID,'ACTULIZACION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
   	IF DELETING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
    'LEGALES',:OLD.ID,'BORRADO',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
END;



/*AUIDOTORIA LIMITES_BLOQUEOS*/

CREATE OR REPLACE TRIGGER TG_AUDITORIA_LIMITES_BLOQUEOS
AFTER INSERT OR UPDATE OR DELETE ON LIMITES_BLOQUEOS
FOR EACH ROW
BEGIN 
	
	IF INSERTING THEN 
	INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'LIMITES_BLOQUEOS',:NEW.ID,'INSERCION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');
	
    END IF;
   
   	IF UPDATING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'LIMITES_BLOQUEOS',:NEW.ID,'ACTULIZACION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
   	IF DELETING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
    'LIMITES_BLOQUEOS',:OLD.ID,'BORRADO',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
END;


/*AUIDOTORIA MEDIO_PAGO*/

CREATE OR REPLACE TRIGGER TG_AUDITORIA_MEDIO_PAGO
AFTER INSERT OR UPDATE OR DELETE ON MEDIO_PAGO
FOR EACH ROW
BEGIN 
	
	IF INSERTING THEN 
	INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'MEDIO_PAGO',:NEW.ID,'INSERCION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');
	
    END IF;
   
   	IF UPDATING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'MEDIO_PAGO',:NEW.ID,'ACTULIZACION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
   	IF DELETING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
    'MEDIO_PAGO',:OLD.ID,'BORRADO',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
END;


/*AUIDOTORIA PAISES*/

CREATE OR REPLACE TRIGGER TG_AUDITORIA_PAISES
AFTER INSERT OR UPDATE OR DELETE ON PAISES
FOR EACH ROW
BEGIN 
	
	IF INSERTING THEN 
	INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'PAISES',:NEW.ID,'INSERCION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');
	
    END IF;
   
   	IF UPDATING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'PAISES',:NEW.ID,'ACTULIZACION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
   	IF DELETING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
    'PAISES',:OLD.ID,'BORRADO',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
END;


/*AUIDOTORIA PREFERENCIAS*/

CREATE OR REPLACE TRIGGER TG_AUDITORIA_PREFERENCIAS
AFTER INSERT OR UPDATE OR DELETE ON PREFERENCIAS
FOR EACH ROW
BEGIN 
	
	IF INSERTING THEN 
	INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'PREFERENCIAS',:NEW.ID,'INSERCION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');
	
    END IF;
   
   	IF UPDATING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'PREFERENCIAS',:NEW.ID,'ACTULIZACION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
   	IF DELETING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
    'PREFERENCIAS',:OLD.ID,'BORRADO',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
END;

/*AUIDOTORIA RETIROS*/

CREATE OR REPLACE TRIGGER TG_AUDITORIA_RETIROS
AFTER INSERT OR UPDATE OR DELETE ON RETIROS
FOR EACH ROW
BEGIN 
	
	IF INSERTING THEN 
	INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'RETIROS',:NEW.ID,'INSERCION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');
	
    END IF;
   
   	IF UPDATING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'RETIROS',:NEW.ID,'ACTULIZACION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
   	IF DELETING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
    'RETIROS',:OLD.ID,'BORRADO',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
END;


/*AUIDOTORIA TIPOS_USUARIOS*/

CREATE OR REPLACE TRIGGER TG_AUDITORIA_TIPOS_USUARIOS
AFTER INSERT OR UPDATE OR DELETE ON TIPOS_APUESTAS
FOR EACH ROW
BEGIN 
	
	IF INSERTING THEN 
	INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'TIPOS_APUESTAS',:NEW.ID,'INSERCION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');
	
    END IF;
   
   	IF UPDATING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'TIPOS_APUESTAS',:NEW.ID,'ACTULIZACION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
   	IF DELETING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
    'TIPOS_APUESTAS',:OLD.ID,'BORRADO',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
END;



/*AUIDOTORIA USUARIOS*/

CREATE OR REPLACE TRIGGER TG_AUDITORIA_USUARIOS
AFTER INSERT OR UPDATE OR DELETE ON USUARIOS
FOR EACH ROW
BEGIN 
	
	IF INSERTING THEN 
	INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'USUARIOS',:NEW.ID,'INSERCION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');
	
    END IF;
   
   	IF UPDATING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
   'USUARIOS',:NEW.ID,'ACTULIZACION',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
   	IF DELETING THEN 
		INSERT INTO AUDITORIA (TABLA,RECORD_ID,ACTION,USUARIO,IP,registro_activo) VALUES (
    'USUARIOS',:OLD.ID,'BORRADO',USER,SYS_CONTEXT('USERENV','IP_ADDRESS'),'Y');

    END IF;
   
END;



