create OR REPLACE PROCEDURE finaliza_partido (id_partido number)
IS  
  
BEGIN 
  UPDATE CRONOGRAMA_PARTIDOS SET ESTADO = 'FINALIZADO' WHERE ID = id_partido; 
END; 




-- select * from cronograma_partidos;
--SELECT SALDO FROM USUARIOS WHERE ID = 2;
--SELECT * FROM APUESTAS WHERE ID_USUARIO = 2;
--SELECT * FROM DETALLE_APUESTA WHERE ESTADO = 'GANADA'
--SELECT * FROM TIPOS_APUESTAS  WHERE ID_CRONOGRAMA = 2;
--SELECT * FROM CRONOGRAMA_PARTIDOS  WHERE ID = 2;
--execute finaliza_partido(2);